name: Build and Publish Storybook to GitHub Pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Install and build
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
        with:
          install_command: npm i
          build_command: npm run build-storybook
          path: storybook-static
          checkout: false
